/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cp2_lab_project;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author 1234
 */
public class Buy_LoadBalance extends javax.swing.JFrame {
    
    
    DefaultComboBoxModel<String> combobox_model = new DefaultComboBoxModel<>(Valuables.getValuables());
    Wallet wallet_frame = new Wallet();
    
    

    /**
     * Creates new form Buy_Sell
     */
    public Buy_LoadBalance() {
        
        initComponents();
        wallet_frame.setVisible(true);
        jComboBox1.setModel(combobox_model);
        
        try{
        jComboBox1.setSelectedItem(Valuables.getSelected_value());// helps to get selected valuables from wallet page and we assign it to selected_vals_value_lbl label
        }catch(Exception e){ // if noyhing selected in wallet page
            jComboBox1.setSelectedItem("Bitcoin");
        }
        
        selected_val_lbl.setText((String) jComboBox1.getSelectedItem());
        selected_vals_value_lbl.setText(Valuables.selecteds_value((String) jComboBox1.getSelectedItem())+"$");
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selected_val_lbl = new javax.swing.JLabel();
        selected_vals_value_lbl = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        buy_sth_txt = new javax.swing.JTextField();
        buy_sth_bttn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Load_Balance_txt = new javax.swing.JTextField();
        Top_Up_Balance_bttn = new javax.swing.JButton();
        max_buy_bttn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buy&Balance");

        selected_val_lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selected_val_lbl.setText("Bitcoin");

        selected_vals_value_lbl.setFont(selected_vals_value_lbl.getFont().deriveFont((float)14));
        selected_vals_value_lbl.setText("88000");

        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1İtemStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("How Many Do You Want To Buy?");

        buy_sth_bttn.setText("Buy");
        buy_sth_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buy_sth_bttnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Top Up Balance:");

        Top_Up_Balance_bttn.setText("Top Up");
        Top_Up_Balance_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Top_Up_Balance_bttnActionPerformed(evt);
            }
        });

        max_buy_bttn.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        max_buy_bttn.setText("Max Buy");
        max_buy_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                max_buy_bttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Load_Balance_txt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buy_sth_txt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(max_buy_bttn, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(selected_val_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(selected_vals_value_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buy_sth_bttn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Top_Up_Balance_bttn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(51, 51, 51))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selected_val_lbl)
                    .addComponent(selected_vals_value_lbl)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buy_sth_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buy_sth_bttn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(max_buy_bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Load_Balance_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Top_Up_Balance_bttn))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1İtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1İtemStateChanged
        selected_val_lbl.setText((String)jComboBox1.getSelectedItem());
        selected_vals_value_lbl.setText(Valuables.selecteds_value((String) jComboBox1.getSelectedItem())+"$");
    }//GEN-LAST:event_jComboBox1İtemStateChanged

    private void buy_sth_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buy_sth_bttnActionPerformed
    try{  
        double balance = UserManager.get_current_user().getBalance();
        double unitprice=Double.parseDouble(Valuables.selecteds_value(selected_val_lbl.getText()));
        double piece = Double.parseDouble(buy_sth_txt.getText());
        if(balance - unitprice*piece >= 0&&piece !=0){ // to check users balance is enough to do that investment?
            if(JOptionPane.showConfirmDialog(rootPane, "You will pay "+unitprice*piece+" $")==0){
            UserManager.get_current_user().buy(selected_val_lbl.getText(), Integer.parseInt(buy_sth_txt.getText()),unitprice);
            wallet_frame.dispose();
            this.dispose();
            Wallet new_wallet_frame = new Wallet();
            new_wallet_frame.setVisible(true);
            }   
        }else if(piece==0)
                        JOptionPane.showMessageDialog(rootPane, " Enter amount more than zero");

        else{
            JOptionPane.showMessageDialog(rootPane, "Your balance is not enough, you can add money to your account");
        }
        
    
    }
    catch(NumberFormatException e){// if the text field is empty
        JOptionPane.showMessageDialog(rootPane, "Please enter a numeric value");
    
    }
    catch(Exception e){
        JOptionPane.showMessageDialog(rootPane, "Decrease the number which you try to buy");
    
    }
    }//GEN-LAST:event_buy_sth_bttnActionPerformed

    private void Top_Up_Balance_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Top_Up_Balance_bttnActionPerformed
        try {
            if (Integer.parseInt(Load_Balance_txt.getText()) < 0) { // to handle enterin negative balance
                JOptionPane.showMessageDialog(rootPane, "You cannot add negative balance");
            }else {
                
                UserManager.get_current_user().top_up_balance(Integer.parseInt(Load_Balance_txt.getText()));
                wallet_frame.dispose();
                Wallet new_wallet_frame = new Wallet();
                new_wallet_frame.setVisible(true);
                this.dispose();
                Buy_LoadBalance new_frame = new Buy_LoadBalance();
                new_frame.setVisible(true);
                        
                
                
            }
        }catch (NumberFormatException e) {// if the text field is empty
            JOptionPane.showMessageDialog(rootPane, "Please enter a numeric value");

        }catch (Exception e) { // to handle entering more than integers capacitys
            JOptionPane.showMessageDialog(rootPane, "Please try to add less than 100.000 or you already have a lot of money");

        }
    }//GEN-LAST:event_Top_Up_Balance_bttnActionPerformed

    private void max_buy_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_max_buy_bttnActionPerformed
       if((int)(UserManager.get_current_user().getBalance() / Double.parseDouble(Valuables.selecteds_value((String) jComboBox1.getSelectedItem())))<100000)
        buy_sth_txt.setText(String.valueOf((int)(UserManager.get_current_user().getBalance() / Double.parseDouble(Valuables.selecteds_value((String) jComboBox1.getSelectedItem())))));
       else
           buy_sth_txt.setText("100000");
    }//GEN-LAST:event_max_buy_bttnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buy_LoadBalance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buy_LoadBalance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buy_LoadBalance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buy_LoadBalance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buy_LoadBalance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Load_Balance_txt;
    private javax.swing.JButton Top_Up_Balance_bttn;
    private javax.swing.JButton buy_sth_bttn;
    private javax.swing.JTextField buy_sth_txt;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton max_buy_bttn;
    private javax.swing.JLabel selected_val_lbl;
    private javax.swing.JLabel selected_vals_value_lbl;
    // End of variables declaration//GEN-END:variables
}
