/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cp2_lab_project;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author 1234
 */
public class Sell extends javax.swing.JFrame {
    Wallet wallet_frame = new Wallet();
    DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();

    /**
     * Creates new form Sell
     */
    public Sell() {
        initComponents();
        wallet_frame.setVisible(true);
        
        
        for (int i = 0; i < Valuables.getValuables().length; i++) {// adding users investments to combobox
            if(UserManager.get_current_user().what_have()[i]!=0)
                model.addElement(String.valueOf(Valuables.getValuables()[i]));
            
        }
        jComboBox1.setModel(model);
        
        try{
            jComboBox1.setSelectedItem(Valuables.getSelected_value());
        }
        catch(Exception e){
             jComboBox1.setSelectedItem("Bitcoin");
        }
        
        selected_val_lbl.setText((String) jComboBox1.getSelectedItem());
        selected_vals_value_lbl.setText(Valuables.selecteds_value((String) jComboBox1.getSelectedItem())+"$");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selected_val_lbl = new javax.swing.JLabel();
        selected_vals_value_lbl = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        sell_sth_txt = new javax.swing.JTextField();
        sell_sth_bttn = new javax.swing.JButton();
        sell_all_bttn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sell");

        selected_val_lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selected_val_lbl.setText("Bitcoin");

        selected_vals_value_lbl.setFont(selected_vals_value_lbl.getFont().deriveFont((float)14));
        selected_vals_value_lbl.setText("88000");

        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1İtemStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("How Many Do You Want To Sell?");

        sell_sth_bttn.setText("Sell");
        sell_sth_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sell_sth_bttnActionPerformed(evt);
            }
        });

        sell_all_bttn.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        sell_all_bttn.setText("Sell All");
        sell_all_bttn.setMaximumSize(new java.awt.Dimension(73, 24));
        sell_all_bttn.setMinimumSize(new java.awt.Dimension(73, 24));
        sell_all_bttn.setPreferredSize(new java.awt.Dimension(73, 24));
        sell_all_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sell_all_bttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(sell_all_bttn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sell_sth_txt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                                .addGap(62, 62, 62))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(selected_val_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(selected_vals_value_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sell_sth_bttn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(51, 51, 51))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selected_val_lbl)
                    .addComponent(selected_vals_value_lbl)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sell_sth_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sell_sth_bttn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sell_all_bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1İtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1İtemStateChanged
        selected_val_lbl.setText((String)jComboBox1.getSelectedItem());
        selected_vals_value_lbl.setText(Valuables.selecteds_value((String) jComboBox1.getSelectedItem())+"$");
    }//GEN-LAST:event_jComboBox1İtemStateChanged

    private void sell_sth_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sell_sth_bttnActionPerformed
      try{
          if(Integer.parseInt(sell_sth_txt.getText())>UserManager.get_current_user().what_have()[Valuables.index_Of(selected_val_lbl.getText())])
              JOptionPane.showMessageDialog(rootPane, "You cannot sell more than you have");
          else{
              if(JOptionPane.showConfirmDialog(rootPane, "You will get "+Double.parseDouble(Valuables.selecteds_value((String) jComboBox1.getSelectedItem()))*Integer.parseInt(sell_sth_txt.getText())+" $")==0){
              UserManager.get_current_user().sell(selected_val_lbl.getText(),Integer.parseInt(sell_sth_txt.getText()) ,Double.parseDouble(Valuables.selecteds_value(selected_val_lbl.getText())));
              wallet_frame.dispose();
              Wallet new_wallet_frame = new Wallet();
              new_wallet_frame.setVisible(true);
              } 
          }
              
          
      }catch(NumberFormatException e){
                  JOptionPane.showMessageDialog(rootPane, "Please enter a numeric value");

      }
      catch(Exception e){
          JOptionPane.showMessageDialog(rootPane, "Please enter everything carefully");
                  
      
      }
        
    }//GEN-LAST:event_sell_sth_bttnActionPerformed

    private void sell_all_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sell_all_bttnActionPerformed
       
        sell_sth_txt.setText(String.valueOf((int)(UserManager.get_current_user().what_have()[Valuables.index_Of(selected_val_lbl.getText())])));
        
    }//GEN-LAST:event_sell_all_bttnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sell().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel selected_val_lbl;
    private javax.swing.JLabel selected_vals_value_lbl;
    private javax.swing.JButton sell_all_bttn;
    private javax.swing.JButton sell_sth_bttn;
    private javax.swing.JTextField sell_sth_txt;
    // End of variables declaration//GEN-END:variables
}
