/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cp2_lab_project;

import java.util.Locale;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author 1234
 */
public class Wallet extends javax.swing.JFrame {
    DefaultTableModel table_model = new DefaultTableModel();//left table
    DefaultTableModel table_model2 = new DefaultTableModel();//right table
    
    
    /**
     * Creates new form wallet
     */
    @SuppressWarnings("empty-statement")
    public Wallet() {
        
        String[] identifiers ={"Name","Unit Price","Piece","Total($)"}; // there is a change in the plan:)
        String[] identifiers2 ={"Name","Unit Price"}; 
        table_model.setColumnIdentifiers(identifiers);
        table_model2.setColumnIdentifiers(identifiers2); // adding identifiers
        


        
        
        initComponents();

        
        table_users_valuables.setModel(table_model);
        table_all_valuables.setModel(table_model2);
        



        
        String[] table_array= new String[5];
        String[] table_array2= new String[2];
        double all_total=0;
        
        
        for (int i = 0; i < Valuables.getValuables().length; i++) { // to add table values
           
            
           if(UserManager.get_current_user().what_have()[i]!=0){ // if user has sth add it to the first table
                table_array[0]= Valuables.getValuables()[i];
                table_array[1] = Valuables.selecteds_value(table_array[0]);
                table_array[2] = String.valueOf(UserManager.get_current_user().what_have()[i]);
                table_array[3] = String.format(Locale.ENGLISH, "%.3f",Double.parseDouble(Valuables.selecteds_value(table_array[0]).replace(",", "."))* UserManager.get_current_user().what_have()[i]);

               
                table_model.addRow(table_array);
                all_total += Double.valueOf(table_array[3]);
            
            }else{// if user do not have that add it to right table
               table_array2[0]=Valuables.getValuables()[i];
               table_array2[1] = String.format("%.3f",Double.parseDouble(Valuables.selecteds_value(table_array2[0])));
               table_model2.addRow(table_array2);
           
           }
           
           

        }

        
        
        total_lbl.setText(String.valueOf(String.format("%.2f",all_total))+"$");
        balance_lbl.setText(String.valueOf(String.format("%.2f",UserManager.get_current_user().getBalance()))+"$");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_users_valuables = new javax.swing.JTable();
        buy_bttn = new javax.swing.JButton();
        sell_bttn = new javax.swing.JButton();
        refresh_bttn = new javax.swing.JButton();
        balance_lbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        total_lbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_all_valuables = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Wallet");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Wallet Balance:");

        table_users_valuables.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table_users_valuables);

        buy_bttn.setText("Buy");
        buy_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buy_bttnActionPerformed(evt);
            }
        });

        sell_bttn.setText("Sell");
        sell_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sell_bttnActionPerformed(evt);
            }
        });

        refresh_bttn.setText("Refresh");
        refresh_bttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh_bttnActionPerformed(evt);
            }
        });

        balance_lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Total Valuables:");

        total_lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel3.setText("In your wallet:");

        table_all_valuables.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(table_all_valuables);

        jLabel4.setText("Other valuables:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(buy_bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(sell_bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(428, 428, 428)
                        .addComponent(refresh_bttn))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(total_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(balance_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(198, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sell_bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(total_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(balance_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buy_bttn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(refresh_bttn))))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buy_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buy_bttnActionPerformed
        
       try{// if user selected sth in the table we hold that data and after that in the buy or sell page we firstly appear that
        Valuables.User_selected_val(String.valueOf(table_users_valuables.getValueAt(table_users_valuables.getSelectedRow(), 0)));// helps to hold selected valuable and we send that info to Buy_LoadBalance
       }
       catch(Exception e){}
        Buy_LoadBalance buy_frame = new Buy_LoadBalance();
        buy_frame.setVisible(true);
        this.dispose();
        
        
    }//GEN-LAST:event_buy_bttnActionPerformed

    private void refresh_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh_bttnActionPerformed
       
        this.setVisible(false);
        Valuables.change_values();
        Wallet wallet_frame = new Wallet();
        wallet_frame.setVisible(true);
        
        
    }//GEN-LAST:event_refresh_bttnActionPerformed

    private void sell_bttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sell_bttnActionPerformed
        try{     // if user selected sth in the table we hold that data and after that in the buy or sell page we firstly appear that

        Valuables.User_selected_val(String.valueOf(table_users_valuables.getValueAt(table_users_valuables.getSelectedRow(), 0)));// helps to hold selected valuable and we send that info to Sell frame
       }
       catch(Exception e){
       
       }
        Sell sell_frame = new Sell();
        sell_frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_sell_bttnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Wallet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Wallet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Wallet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Wallet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Wallet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel balance_lbl;
    private javax.swing.JButton buy_bttn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton refresh_bttn;
    private javax.swing.JButton sell_bttn;
    private javax.swing.JTable table_all_valuables;
    private javax.swing.JTable table_users_valuables;
    private javax.swing.JLabel total_lbl;
    // End of variables declaration//GEN-END:variables
}
